### ISSUE TITLE
No matter what I do plugin can't find settings

### ISSUE THREAD

**Issue by Ingegneus** [tjjfvi/OctoPrint-SlicerSettingsTab#10]
I have done the necessary setup in cura and the parser, but this tab always looks like this
![image](https://github.com/larsjuhw/OctoPrint-SlicerSettingsTab/assets/78076361/9dd4a40b-197b-4147-b29d-fdf0c4e4e5cf)

I think this plugin would be very handy

**Comment by Ingegneus** [comment]
ok my bad I didn't notice that the regex in [OctoPrint-SlicerSettingsParser](https://github.com/larsjuhw/OctoPrint-SlicerSettingsParser) doesn't match the format in [this](https://gist.github.com/tjjfvi/75210b2ed20ed194d6eab48bf70c4f12) list

**Comment by larsjuhw** [comment]
My fault. Fixed the regex in the README for SlicerSettingsParser.
