### ISSUE TITLE
Problem with SlicerSettingsTab working after I use MutliColors plugin to insert Color Changes

### ISSUE THREAD

**Issue by rholmes376** [tjjfvi/OctoPrint-SlicerSettingsTab#6]
I use MultiColor plugin to insert M117 commands to announce what color filament is next to load.

I also use your plugin SlicerSettingsTab to show the color Sequence from the NOTES from Prusa Slicer. 

Once I insert the M117 command via MultiColor,  SlicerSettingsTab cannot read the gcode file with the _MULTI append to the the file name from Multicolor.   SlicerSettingsTab says "No Slicer Settings (for this file)"  

I could email you a gcode file before MULTICODE was used and one after if you like.

Randy

**Comment by tjjfvi** [comment]
@rholmes376 If you would send me the gcode (as a gist / pastebin / etc.) before and after that would be great.

**Comment by rholmes376** [comment]
Here are the gcodes.    The one with MULTI at the end is what the MULTI
Colors Plugin inserted....

**Comment by tjjfvi** [comment]
@rholmes376 Unfortunately the attachments didn't go through; can you upload them to https://pastebin.com/ or https://gist.github.com/ (or similar)?

**Comment by rholmes376** [comment]
Here is the gist I created:   <script src="
https://gist.github.com/rholmes376/b510c3a3187249d6c11eb0e7367ba37a.js
"></script>

**Comment by tjjfvi** [comment]
Can you just make two gists of the before and after Gcode?

**Comment by rholmes376** [comment]
Not sure how to do gist if that last did not work.  Here is the zip file of
the 2 gcode files.
